version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123456
    ports:
      - 27017:27017
    volumes:
      - /opt/mongo/data/data:/data/db
      - /opt/mongo/data/log:/var/log/mongodb
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123456
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: false
      #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      #ME_CONFIG_BASICAUTH_USERNAME: root
      #ME_CONFIG_BASICAUTH_PASSWORD: abc123456
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge